---
title: "Concursos da Marinha"
author: "igorkf"
date: "`r paste('Última atualização:', format(as.Date(file.info('base_marinha.xlsx')$mtime), format = '%d/%m/%Y'))`"
output: 
  html_document:
    includes:
       in_header: GA_script.html
---


```{r, include = F}

library(tidyverse)
knitr::opts_chunk$set(echo = F)

```



Clique com o botão direito no nome do concurso e abra em uma nova aba.  
Você pode digitar alguma palavra chave no campo Procurar. 
```{r}

# http://cdn.datatables.net/plug-ins/1.10.11/i18n/Portuguese.json
portugues <-
jsonlite::fromJSON(
'{
	"sProcessing":   "A processar...",
	"sLengthMenu":   "Mostrar _MENU_ registos",
	"sZeroRecords":  "Não foram encontrados resultados",
	"sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registos",
	"sInfoEmpty":    "Mostrando de 0 até 0 de 0 registos",
	"sInfoFiltered": "(filtrado de _MAX_ registos no total)",
	"sInfoPostFix":  "",
	"sSearch":       "Procurar:",
	"sUrl":          "",
	"oPaginate": {
	    "sFirst":    "Primeiro",
	    "sPrevious": "Anterior",
	    "sNext":     "Seguinte",
	    "sLast":     "Último"
	}
}'
)

readxl::read_xlsx("base_marinha.xlsx") %>%
  rename(Concurso = concurso) %>% 
  DT::datatable(rownames = F, escape = F, extensions = c('Scroller', 'FixedHeader'),
                class = 'cell-border stripe nowrap',
                options = list(pageLength = 20, ordering = F,
                               scrollY = 300, scroller = T, scrollX = F,
                language = portugues))

```

